version: '3.8'

services:

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'django_cont'
    ports:
      - "8000:8000"
    command: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && gunicorn BangHouse.wsgi:application --bind 0.0.0.0:8000"]

  nginx:
    build:
      context: ./nginx
    image: nginx
    container_name: 'nginx_cont'
    ports:
      - "80:80"
    depends_on:
      - django_app
